name: Helm Deploy Release
description: Deploys a helm chart to Kubernetes
author: Froxz
branding:
  color: blue
  icon: anchor
inputs:
  release:
    description: Helm release name. Will be combined with track if set. (required)
    required: true
  namespace:
    description: Kubernetes namespace name. (required)
    required: true
  chart:
    description: Path to Helm chart. (required)
    required: true
  task:
    description: Task name. If the task is "remove" it will remove the configured helm release.
    required: false
  dry-run:
    description: Simulate an upgrade.
    required: false
  atomic:
    description: If true, upgrade process rolls back changes made in case of failed upgrade. Defaults to true.
    required: false
  values:
    description: Value files to apply to the helm chart. Expects JSON encoded array or a string.
    required: false
  vars:
    description: Variables to include in value file interpolation. Expects JSON encoded map.
    required: false
  secrets:
    description: Secret variables to include in value file interpolation. Expects JSON encoded map.
    required: false
  chart-version:
    description: Chart Version
    required: false
  version:
    description: Version of the app, usually commit sha works here.
    required: false
  timeout:
    description: A Go duration value to wait for Kubernetes commands to complete. This defaults to 5m0s.
    required: false
  args:
    description: List of deploy-time args
    required: false
runs:
  using: docker
  image: docker://ghcr.io/sergkeim/helm-deploy:v1.2.0
